-- MySQL Script generated by MySQL Workbench
-- Fri Oct  7 22:33:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pandoraweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pandoraweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pandoraweb` DEFAULT CHARACTER SET utf8 COLLATE utf8_hungarian_ci ;
USE `pandoraweb` ;

-- -----------------------------------------------------
-- Table `pandoraweb`.`GeneroUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pandoraweb`.`GeneroUsuarios` (
  `IDGeneroUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreGenero` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IDGeneroUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pandoraweb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pandoraweb`.`Rol` (
  `IDRol` INT NOT NULL AUTO_INCREMENT,
  `NombreRol` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`IDRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pandoraweb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pandoraweb`.`Usuarios` (
  `IDUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(10) NOT NULL,
  `primerNombre` VARCHAR(15) NOT NULL,
  `segundoNombre` VARCHAR(15) NOT NULL,
  `apellidos` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(15) NOT NULL,
  `generoUsuarioId` INT NOT NULL,
  `rolId` INT NOT NULL,
  PRIMARY KEY (`IDUsuario`),
  INDEX `idGenero_idx` (`generoUsuarioId` ASC) VISIBLE,
  INDEX `rolId_idx` (`rolId` ASC) VISIBLE,
  CONSTRAINT `idGenero_user`
    FOREIGN KEY (`generoUsuarioId`)
    REFERENCES `pandoraweb`.`GeneroUsuarios` (`IDGeneroUsuario`),
  CONSTRAINT `rolId`
    FOREIGN KEY (`rolId`)
    REFERENCES `pandoraweb`.`Rol` (`IDRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pandoraweb`.`TelefonoUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pandoraweb`.`TelefonoUsuarios` (
  `IDTelefono` INT NOT NULL AUTO_INCREMENT,
  `numeroTelefono` VARCHAR(15) NOT NULL,
  `UsuarioId` INT NOT NULL,
  PRIMARY KEY (`IDTelefono`),
  INDEX `UsuarioId_idx` (`UsuarioId` ASC) VISIBLE,
  CONSTRAINT `UsuarioId`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `pandoraweb`.`Usuarios` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
