-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 19:27:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pandoraWeb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pandoraWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pandoraWeb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pandoraWeb` ;

-- -----------------------------------------------------
-- Table `ClasificacionEdades`
-- -----------------------------------------------------
CREATE TABLE `ClasificacionEdades` (
  `IDClasificacionEdades` INT NOT NULL AUTO_INCREMENT,
  `nombreClasificacion` VARCHAR(7) NOT NULL,
  `descripcionClasificacion` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`IDClasificacionEdades`),
  UNIQUE INDEX `idClasificacionEdades_UNIQUE` (`IDClasificacionEdades` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table ` `.`Pais`
-- -----------------------------------------------------
CREATE TABLE `Pais` (
  `IDPais` INT NOT NULL AUTO_INCREMENT,
  `codigoIso` VARCHAR(5) NOT NULL,
  `nombrePais` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idPais_UNIQUE` (`IDPais` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Series`
-- -----------------------------------------------------
CREATE TABLE `Series` (
  `IDSeries` INT NOT NULL AUTO_INCREMENT,
  `nombreSerie` VARCHAR(30) NOT NULL,
  `Sinopsis` VARCHAR(150) NOT NULL,
  `anoEstreno` DATE NOT NULL,
  `paisId` INT NOT NULL,
  `generoId` INT NOT NULL,
  `calidadId` INT NOT NULL,
  `capituloId` INT NOT NULL,
  `idiomaId` INT NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`IDSeries`),
  UNIQUE INDEX `idSerie_UNIQUE` (`IDSeries` ASC) VISIBLE,
  INDEX `idPais_idx` (`paisId` ASC) VISIBLE,
  INDEX `idEdad_idx` (`edad` ASC) VISIBLE,
  CONSTRAINT `idEdad_series`
    FOREIGN KEY (`edad`)
    REFERENCES `pandora_web`.`ClasificacionEdades` (`IDClasificacionEdades`),
  CONSTRAINT `idPaises_series`
    FOREIGN KEY (`paisId`)
    REFERENCES `pandora_web`.`Pais` (`IDPais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Actores`
-- -----------------------------------------------------
CREATE TABLE `Actores` (
  `IDActores` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `idPelicula` INT NOT NULL,
  `SerieID` INT NOT NULL,
  PRIMARY KEY (`IDActores`),
  INDEX `serieId_idx` (`SerieID` ASC) VISIBLE,
  CONSTRAINT `serieId`
    FOREIGN KEY (`SerieID`)
    REFERENCES `pandora_web`.`Series` (`IDSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `calidadSeries`
-- -----------------------------------------------------
CREATE TABLE `calidadSeries` (
  `IDCalidad` INT NOT NULL AUTO_INCREMENT,
  `nombreCalidad` VARCHAR(20) NOT NULL,
  `descipcion` VARCHAR(80) NOT NULL,
  `SerieID` INT NOT NULL,
  PRIMARY KEY (`IDCalidad`),
  UNIQUE INDEX `idCalidad_UNIQUE` (`IDCalidad` ASC) VISIBLE,
  INDEX `serieId_idx` (`SerieID` ASC) VISIBLE,
  CONSTRAINT `serieId`
    FOREIGN KEY (`SerieID`)
    REFERENCES `pandora_web`.`Series` (`IDSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Capitulos`
-- -----------------------------------------------------
CREATE TABLE `Capitulos` (
  `IDCapitulo` INT NOT NULL AUTO_INCREMENT,
  `numeroCapitulo` INT NOT NULL,
  `SerieID` INT NOT NULL,
  PRIMARY KEY (`IDCapitulo`),
  UNIQUE INDEX `idCapitulo_UNIQUE` (`IDCapitulo` ASC) VISIBLE,
  INDEX `serieId_idx` (`SerieID` ASC) VISIBLE,
  CONSTRAINT `serieId`
    FOREIGN KEY (`SerieID`)
    REFERENCES `pandora_web`.`Series` (`IDSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GeneroSerie`
-- -----------------------------------------------------
CREATE TABLE `GeneroSerie` (
  `IDGeneroPeliculaSerie` INT NOT NULL AUTO_INCREMENT,
  `nombreGenero` VARCHAR(20) NOT NULL,
  `SerieID` INT NOT NULL,
  PRIMARY KEY (`IDGeneroPeliculaSerie`),
  UNIQUE INDEX `idGeneroPelicula_UNIQUE` (`IDGeneroPeliculaSerie` ASC) VISIBLE,
  INDEX `serieId_idx` (`SerieID` ASC) VISIBLE,
  CONSTRAINT `serieId`
    FOREIGN KEY (`SerieID`)
    REFERENCES `pandora_web`.`Series` (`IDSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Idioma`
-- -----------------------------------------------------
CREATE TABLE `Idioma` (
  `IDIdioma` INT NOT NULL AUTO_INCREMENT,
  `nombreIdioma` VARCHAR(45) NOT NULL,
  `SerieID` INT NOT NULL,
  PRIMARY KEY (`IDIdioma`),
  UNIQUE INDEX `idIdioma_UNIQUE` (`IDIdioma` ASC) VISIBLE,
  INDEX `serieId_idx` (`SerieID` ASC) VISIBLE,
  CONSTRAINT `serieId`
    FOREIGN KEY (`SerieID`)
    REFERENCES `pandora_web`.`Series` (`IDSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Plataformas`
-- -----------------------------------------------------
CREATE TABLE `Plataformas` (
  `IDPlataforma` INT NOT NULL AUTO_INCREMENT,
  `nombrePlataforma` VARCHAR(30) NOT NULL,
  `SerieID` INT NOT NULL,
  PRIMARY KEY (`IDPlataforma`),
  UNIQUE INDEX `idPlataforma_UNIQUE` (`IDPlataforma` ASC) VISIBLE,
  INDEX `serieId_idx` (`SerieID` ASC) VISIBLE,
  CONSTRAINT `serieId`
    FOREIGN KEY (`SerieID`)
    REFERENCES `pandora_web`.`Series` (`IDSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Temporadas`
-- -----------------------------------------------------
CREATE TABLE `Temporadas` (
  `IDTemporada` INT NOT NULL AUTO_INCREMENT,
  `nombreTemporada` VARCHAR(15) NOT NULL,
  `SerieID` INT NOT NULL,
  PRIMARY KEY (`IDTemporada`),
  UNIQUE INDEX `idTemporada_UNIQUE` (`IDTemporada` ASC) VISIBLE,
  INDEX `serieId_idx` (`SerieID` ASC) VISIBLE,
  CONSTRAINT `serieId`
    FOREIGN KEY (`SerieID`)
    REFERENCES `pandora_web`.`Series` (`IDSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
